version: "3"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=ac_bank_database
      - POSTGRES_USER=my_django_user
      - POSTGRES_PASSWORD=12345
  dj:
    container_name: dj
    build: django
    command: python manage.py runserver 0.0.0.0:80
    volumes:
      - ./django:/code
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS=dev