# Generated by Django 3.2.6 on 2021-07-31 21:22

import datetime
from django.db import migrations, models


"""
class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=50)),
                ('created_on', models.DateField(default=datetime.date.today)),
                ('due_date', models.DateField(default=datetime.date.today)),
            ],
            options={
                'db_table': 'task',
                'ordering': ['id'],
            },
        ),
    ]


"""


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('project_status', models.CharField("Project Status", max_length=50)),
                ('project_country', models.CharField("Project Country", max_length=50)),
                ('year', models.CharField("year", max_length=50)),
                ('month', models.CharField("month", max_length=50)),
                ('project_name', models.CharField("Project Name", max_length=50)),
                ('company', models.CharField("company", max_length=50)),
                ('project_number', models.CharField("Project Number", primary_key = True, max_length=50)),
                ('sector', models.CharField("Project Sector", max_length=50)),
                ('bank', models.CharField("Project Bank", max_length=50)),
                ('url', models.CharField("Project URL", max_length=50)),
                ('loan_amount', models.CharField(db_column="Loan Amount", max_length=50)),
                ('currency', models.CharField(db_column="currency", max_length=50)),	
                ('loan_amount_in_usd', models.CharField(db_column="Loan Amount in USD", max_length=50))

            ],
            options={
                'db_table': 'complaints',
                #'ordering': ['id'],
            },
        ),
    ]

