# Generated by Django 4.0.dev20210628094637 on 2021-08-16 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='bank',
            field=models.CharField(db_column='Project Bank', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='company',
            field=models.CharField(db_column='company', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='month',
            field=models.CharField(db_column='month', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='project_country',
            field=models.CharField(db_column='Project Country', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='project_name',
            field=models.CharField(db_column='Project Name', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='project_number',
            field=models.CharField(db_column='Project Number', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='project_status',
            field=models.CharField(db_column='Project Status', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='sector',
            field=models.CharField(db_column='Project Sector', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='url',
            field=models.CharField(db_column='Project URL', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='year',
            field=models.CharField(db_column='year', max_length=50),
        ),
    ]
